[profile.default]
auto_detect_solc = true
evm_version = "cancun"
src = "src"
out = "out"
libs = ["lib"]
via_ir = true

[profile.metadata]
auto_detect_solc = true
evm_version = "cancun"
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
bytecode_hash = "none"
cbor_metadata = false

[profile.shanghai]
auto_detect_solc = true
evm_version = "shanghai"
src = "src"
out = "out"
libs = ["lib"]
via_ir = true

fs_permissions = [{ access = "read", path = "./"}]

[rpc_endpoints]
amoy = "https://warmhearted-wiser-spring.matic-amoy.quiknode.pro/7672f450baa71d892346bb2fc6845b0331e5c85d/"
holesky = "https://ethereum-holesky.publicnode.com"
arbitrum_sepolia = "https://spring-multi-thunder.arbitrum-sepolia.quiknode.pro/e464b44bbfcfc4069ad869e5fb9fadfd9f56f72f/"
solana_devnet = "https://warmhearted-icy-patina.solana-devnet.quiknode.pro/225e943243dbad5847aa15fd68d350246a52062b/"
debank_testnet = "http://rpc.testnet.debank.com"
manta_testnet = "https://manta-pacific-testnet.drpc.org"
barret = "https://rpc-pop-testnet-barret-oxaolmcfss.t.conduit.xyz"
zksync_sepolia = "https://sepolia.era.zksync.dev"
align_testnet_v2 = "https://align-testnet.rpc.caldera.xyz/http"
mode_testnet = "https://sepolia.mode.network/8R2AbRhkvTrKgGyEWkmbSBGzjKbzKx1cv"
bob = "https://rpc.gobob.xyz/"
goerli = "https://patient-palpable-patron.ethereum-goerli.quiknode.pro/3abdc164e6128752f647dbd9bf7617d0e466b24c/"
gin_testnet = "https://gin-testnet.alt.technology"
frame_testnet = "https://rpc.testnet.frame.xyz/infra-integration-http"
blast_sepolia = "https://fittest-lively-energy.blast-sepolia.quiknode.pro/e862635fdf062b6e592ea79d6af601edb77fe2a2/"
astar_zkyoto = "https://rpc.zkyoto.gelato.digital"
hypr = "https://rpc-testnet.hypr.network/"
hekla = "https://rpc.hekla.taiko.xyz"
op_sepolia = "https://damp-ultra-resonance.optimism-sepolia.quiknode.pro/b6bc41ce6c01e55318cb088b9ade3b8f9af6fa0c/"
garnet = "https://rpc.garnet.qry.live"
ancient8_celestia_testnet = "https://rpcv2-testnet.ancient8.gg/8R2AbRhkvTrKgGyEWkmbSBGzjKbzKx1cv"
atlas = "https://l2-atlas-ltzdfao2b6.t.conduit.xyz"
b3 = "https://sepolia.b3.fun/http"
zora_sepolia = "https://sepolia.rpc.zora.energy"
funki_testnet = "https://funki-testnet.alt.technology"
lisk_sepolia = "https://rpc.sepolia-api.lisk.com"
cloud = "https://rpc-pop-testnet-cloud-fmg1z6e0a9.t.conduit.xyz"
game7_testnet = "https://rpc-game7-testnet-0ilneybprf.t.conduit.xyz"
shape_sepolia = "https://sepolia.shape.network/"
arbitrum_blueberry = "https://rpc.arb-blueberry.gelato.digital"
m_integrations_testnet = "https://rpc-m-integrations-testnet-kn5qqp4tzd.t.conduit-stg.xyz"
sepolia = "https://responsive-flashy-spring.ethereum-sepolia.quiknode.pro/a4e86c916409d39b7b8be85c4a17fab4f26b427e/"
memecoin_2 = "https://rpc-memecoin-2-7m5e84e2pz.t.conduit.xyz"
base_sepolia = "https://sepolia.base.org"
redstone = "https://rpc.redstonechain.com/"
rari = "https://mainnet.rpc.rarichain.org/http"
zksync = "https://convincing-prettiest-frost.zksync-mainnet.quiknode.pro/a14018fec401cbe6626d8a200375555d21a5503e/"
degen = "https://rpc.degen.tips/FkJa1BMrbHboCvbfrCZJH9U5CHWpr3skv"
linea = "https://rpc.linea.build"
avalanche = "https://rough-late-energy.avalanche-mainnet.quiknode.pro/db7a0c340d1807fce83ffbf167b7ef909ab4089b/ext/bc/C/rpc/"
zora = "https://rpc.zora.energy/FkJa1BMrbHboCvbfrCZJH9U5CHWpr3skv"
polygon = "https://solitary-bitter-layer.matic.quiknode.pro/a57a0dbd9436e681cfe0f6806dc835eec0e4c0b5/"
ancient8 = "https://rpc.ancient8.gg/FkJa1BMrbHboCvbfrCZJH9U5CHWpr3skv"
xai = "https://xai-chain.net/rpc"
astar_zkevm = "https://rpc.astar-zkevm.gelato.digital"
mode = "https://mainnet.mode.network/"
gnosis = "https://rpc.gnosis.gateway.fm"
blast = "https://attentive-bitter-river.blast-mainnet.quiknode.pro/f1e17763e996399edd6e03acec1b2dd1ce45b1f1/"
apex = "https://rpc.apex.proofofplay.com/8zMb1iBjJ37VwJkqYjMBg3AvtTbzWEs5q"
funki = "https://rpc-mainnet.funkichain.com"
lisk = "https://rpc.api.lisk.com"
ham = "https://rpc.ham.fun"
solana = "https://wild-magical-darkness.solana-mainnet.quiknode.pro/29d5577cf0695c8ef04abaebf0fa4670fdc3f695/"
onchain_points = "https://rpc-onchain-points-8n0qkkpr2j.t.conduit.xyz"
polygon_zkevm = "https://yolo-proportionate-asphalt.zkevm-mainnet.quiknode.pro/63e56ccf849ce2a176a40f31272baae22965c492/"
arbitrum_nova = "https://distinguished-boldest-layer.nova-mainnet.quiknode.pro/991046398297653a9f0ff1293ce912630986fd5f/"
taiko = "https://taiko.drpc.org"
boba = "https://mainnet.boba.network"
cyber = "https://rpc.cyber.co"
arbitrum = "https://bold-few-mountain.arbitrum-mainnet.quiknode.pro/141c1fd7dd64a97d4d3c52d1487dbbefc55603b3/"
scroll = "https://rpc.scroll.io"
mainnet = "https://multi-hidden-season.quiknode.pro/1330cd9c226307d0f722003a01b68cc844344a39/"
bsc = "https://fabled-black-sanctuary.bsc.quiknode.pro/8dba6ccc07667feafd0dd6064281c2a46ae353ed/"
base = "https://aged-compatible-pine.base-mainnet.quiknode.pro/86247a56f7f36a0f0c0b10eb65061748f66bce7c/"
mint = "https://rpc.mintchain.io"
optimism = "https://quaint-frequent-grass.optimism.quiknode.pro/c5bc8d8cf82b0388642982d6e7a0cfa561c49b0b/"
boss = "https://rpc.boss.proofofplay.com"
bob_testnet = "https://testnet.rpc.gobob.xyz/"
b3_sepolia = "https://sepolia.b3.fun/http"
creator = "https://rpc-creator-335av30doc.t.conduit.xyz"
pop_cloud_testnet = "https://rpc-pop-testnet-cloud-fmg1z6e0a9.t.conduit.xyz"
secret = "https://rpc-secret-xj64ve9mdm.t.conduit.xyz"
mobl3_testnet = "https://sepolia.mobl3.xyz"
alleged_jade_loon = "https://rpc-alleged-jade-loon-fqlx1rs2zw.t.conduit.xyz"
kekchain = "https://rpc-kekchain-lvvulci8ai.t.conduit.xyz"
eclipse_testnet = "https://testnet.dev2.eclipsenetwork.xyz"
zero_testnet = "https://rpc.zerion.io/v1/zero-sepolia"
worldchain = "https://worldchain-mainnet.g.alchemy.com/public"
apechain = "https://apechain.calderachain.xyz/http"
unichain = "https://unichain.drpc.org"
mantle = "https://rpc.mantle.xyz"
berachain = "https://rpc.berachain.com"
sonic = "https://rpc.soniclabs.com"
shape = "https://mainnet.shape.network"
flow = "https://mainnet.evm.nodes.onflow.org"
sei = "https://evm-rpc.sei-apis.com"
perennial = "https://rpc-perennial-lsv53i0ed8.t.conduit.xyz"
story = "https://mainnet.storyrpc.io"
gravity = "https://rpc.gravity.xyz"
soneium = "https://rpc.soneium.org/"
swellchain = "https://swell-mainnet.alt.technology"
sanko = "https://mainnet.sanko.xyz"
game7 = "https://mainnet-rpc.game7.io/"
hychain = "https://rpc.hychain.com/http"
echos = "https://rpc-echos-mainnet-0.t.conduit.xyz"
powerloom = "https://rpc.powerloom.network"
arena_z = "https://rpc.arena-z.gg"
superposition = "https://rpc.superposition.so"
ink = "https://rpc-qnd.inkonchain.com"
forma = "https://rpc.forma.art"
eclipse = "https://mainnetbeta-rpc.eclipse.xyz"
ronin = "https://api.roninchain.com/rpc"
rootstock = "https://public-node.rsk.co"

[etherscan]
# Mainnets
mainnet = { key = "${ETHERSCAN_API_KEY_ETHEREUM}" }
optimism = { key = "${ETHERSCAN_API_KEY_OPTIMISM}" }
polygon = { key = "${ETHERSCAN_API_KEY_POLYGON}" }
gnosis = { key = "${ETHERSCAN_API_KEY_GNOSIS}" }
linea = { key = "${ETHERSCAN_API_KEY_LINEA}" }
bsc = { key = "${ETHERSCAN_API_KEY_BSC}" }
scroll = { key = "${ETHERSCAN_API_KEY_SCROLL}" }
polygon_zkevm = { key = "${ETHERSCAN_API_KEY_POLYGON_ZKEVM}" }
zksync = { key = "0x", url = "https://block-explorer-api.mainnet.zksync.io/api" }
astar_zkevm = { key = "0x", url = "https://astar-zkevm.explorer.startale.com/api" }
base = { key = "${ETHERSCAN_API_KEY_BASE}" }
arbitrum = { key = "${ETHERSCAN_API_KEY_ARBITRUM}" }
arbitrum_nova = { key = "${ETHERSCAN_API_KEY_ARBITRUM_NOVA}" }
zora = { key = "0x", url = "https://explorer.zora.energy/api" }
apex = { key = "0x", url = "https://explorer.apex.proofofplay.com/api" }
blast = { key = "${ETHERSCAN_API_KEY_BLAST}" }
corn = { key = "0x", chain = 21000000, url = "https://api.routescan.io/v2/network/mainnet/evm/21000000/etherscan" }
apechain = { key = "${ETHERSCAN_API_KEY_APECHAIN}", chain = 33139, url = "https://api.apescan.io/api" }
berachain = { key = "${ETHERSCAN_API_KEY_BERA}", chain = 80094, url = "https://api.berascan.com/api" }
# Testnets
sepolia = { key = "${ETHERSCAN_API_KEY_SEPOLIA}" }
base_sepolia = { key = "${ETHERSCAN_API_KEY_BASE_SEPOLIA}" }
blast_sepolia = { key = "${ETHERSCAN_API_KEY_BLAST_SEPOLIA}" }
zora_sepolia = { key = "0x", url = "https://sepolia.explorer.zora.energy/api" }
barret = { key = "${ETHERSCAN_API_KEY_ARBITRUM}", url = "https://70800.testnet.routescan.io/api" }
b3_sepolia = { key = "${ETHERSCAN_API_KEY_ARBITRUM}", url = "https://sepolia.explorer.b3.fun/api" }